ARG NODE_VERSION
FROM node:$NODE_VERSION-alpine

RUN mkdir /app
WORKDIR /app
COPY index.html package.json package-lock.json tsconfig.app.json tsconfig.json tsconfig.node.json vite.config.ts .prettierrc .prettierignore eslint.config.js ./
RUN npm install
